###Note: this piece of code works with csv files that should have been generated by LIWC
###here they are named: "LIWC2015_Goethe_int.csv" (LIWC analysis of the files "Goethe_young_mean.txt" and "Goethe_old.txt"); "LIWC2015_Goethe_ext.csv" (LIWC analysis of the files "Other_authors_young_mean.txt" and "Other_authors_old.txt"), generated by the previous piece of code
###Of course, you should upload a German dictionary into LIWC: Wolf, M. et al. (2008), Computergestützte quantitative Textanalyse: Äquivalenz und Robustheit der deutschen Version des Linguistic Inquiry and Word Count, in Diagnostica 54(2):85-98

library(tidyverse)
library(reshape2)

###prepare LIWC for Goethe
LIWC_Goethe <- read.csv("LIWC2015_Goethe_int.csv")
LIWC_Goethe <- as.data.frame(t(LIWC_Goethe),stringsAsFactors = F)
colnames(LIWC_Goethe) <- c("YoungMiddle", "Old")
LIWC_Goethe <- LIWC_Goethe[-1,]
LIWC_Goethe[,1:2] <- lapply(LIWC_Goethe[,1:2], function(x) as.numeric(x))
LIWC_Goethe$difference <- abs(LIWC_Goethe$Old-LIWC_Goethe$YoungMiddle)
LIWC_Goethe <- LIWC_Goethe[with(LIWC_Goethe, order(-difference)), ]
LIWC_Goethe$LIWC_category <- rownames(LIWC_Goethe)

LIWC_selection <- LIWC_Goethe$LIWC_category[1:8]

###prepare LIWC for Others
LIWC_Others <- read.csv("LIWC2015_Goethe_ext.csv")
LIWC_Others <- as.data.frame(t(LIWC_Others),stringsAsFactors = F)
colnames(LIWC_Others) <- c("YoungMiddle", "Old")
LIWC_Others <- LIWC_Others[-1,]
LIWC_Others[,1:2] <- lapply(LIWC_Others[,1:2], function(x) as.numeric(x))
LIWC_Others$LIWC_category <- rownames(LIWC_Others)

LIWC_Others <- LIWC_Others[which(LIWC_Others$LIWC_category %in% LIWC_selection),]

###compare the two
LIWC_Goethe <- LIWC_Goethe[1:8,]
LIWC_Goethe$difference <- NULL
LIWC_Goethe$author <- "Goethe"
LIWC_Others$author <- "Others"
LIWC_all <- rbind(LIWC_Goethe, LIWC_Others)

###prepare for final graph
LIWC_all <- melt(LIWC_all)

colnames(LIWC_all) <- c("LIWC_Category", "author", "period", "value")

p4 <- ggplot(LIWC_all) +
  geom_bar(aes(LIWC_Category, value, fill = period), stat = "identity", position = "dodge") +
  facet_wrap(~ author, nrow = 1)
p4
ggsave("Goethe_LIWC_analysis.png", p4, height = 6, width = 10)