###Goethe experiment
###Note: the network analysis graph should be generated by using Gephi (https://gephi.org/)
###The following code produces a series of csv files ("Goethe_internal_Gephi.csv" et al.) to be processed with Gephi

library(stylo)

load("Goethe_corpus.RData")
load("Other_authors_corpus.RData")

### define extra functions

dist.cosine.delta <- function(x){
  # z-scoring the input matrix of frequencies
  x = scale(x)
  # computing cosine dissimilarity
  y = as.dist( x %*% t(x) / (sqrt(rowSums(x^2) %*% t(rowSums(x^2)))) )
  # then, turning it into cosine similarity
  z = 1 - y
  # getting the results
  return(z)
}

cut_short <- function(other_authors){
  short <- which(unlist(lapply(other_authors, function(x){length(x)}))<5000)
  other_authors <- other_authors[-short]
  return(other_authors)
}

reduce_name_length <- function(corpus, chars_lim = 20){
  names_tmp <- names(corpus)
  for(i in 1:length(names_tmp)){
    if(nchar(names_tmp[i])>chars_lim)
      names_tmp[i] <- paste(substr(names_tmp[i], 1, chars_lim), "...", sep = "")
  }
  names(corpus) <- names_tmp
  return(corpus)
}

##########
#####Goethe corpus preparation
##########

###Uniform spelling (to avoid issues with alternative spellings)
for(i in 1:length(Goethe_LateStyle_corpus$PG_de_fulltexts)){
  tmp_string <- Goethe_LateStyle_corpus$PG_de_fulltexts[i]
  ##substitute old S
  tmp_string <- gsub("ſ", "s", tmp_string)
  ##substitute umlauts and double S
  tmp_string <- gsub("ä", "ae", tmp_string)
  tmp_string <- gsub("ö", "oe", tmp_string)
  tmp_string <- gsub("ü", "ue", tmp_string)
  tmp_string <- gsub("ß", "ss", tmp_string)
  
  ##substitute line breaks
  tmp_string <- gsub("([a-z])-\\s+([a-z])", "\\1\\2", tmp_string)
  tmp_string <- gsub("([a-z])¬\\s+([a-z])", "\\1\\2", tmp_string)
  
  ##save new version
  Goethe_LateStyle_corpus$PG_de_fulltexts[i] <- tmp_string
  print(i)
}

###prepare Goethe sub-corpus
Goethe_corpus <- list()
for(i in 1:length(Goethe_LateStyle_corpus$PG_de_fulltexts)){
  Goethe_corpus[[i]] <- txt.to.words(Goethe_LateStyle_corpus$PG_de_fulltexts[i])
}
names_tmp <- paste("Goethe", Goethe_LateStyle_corpus$PG_de_texts, Goethe_LateStyle_corpus$first_pub, sep = "_")
names(Goethe_corpus) <- gsub(" ", "", names_tmp)
names(Goethe_corpus) <- gsub(",", "", names_tmp)

###get rid of short texts (limit 5,000 words)
Goethe_short <- which(unlist(lapply(Goethe_corpus, function(x){length(x)}))<5000)
Goethe_LateStyle_corpus <- Goethe_LateStyle_corpus[-Goethe_short,]
Goethe_corpus <- Goethe_corpus[-Goethe_short]

###subdivide in young, mean and old
Goethe_young <- Goethe_corpus[which(Goethe_LateStyle_corpus$first_pub <= 1776)]
Goethe_mean <- Goethe_corpus[which(Goethe_LateStyle_corpus$first_pub > 1776 & Goethe_LateStyle_corpus$first_pub < 1809)]
Goethe_old <- Goethe_corpus[which(Goethe_LateStyle_corpus$first_pub >= 1809)]

###anonymize Goethe's texts, for internal comparison
young_sel <- 1:length(Goethe_young)
mean_sel <- (length(Goethe_young)+1):(length(Goethe_young)+length(Goethe_mean))
old_sel <- (length(Goethe_young)+length(Goethe_mean)+1):(length(Goethe_young)+length(Goethe_mean)+length(Goethe_old))

names(Goethe_young) <- paste("Young", Goethe_LateStyle_corpus$first_pub[young_sel], Goethe_LateStyle_corpus$PG_de_texts[young_sel], sep = "_")
names(Goethe_young) <- gsub(" ", "", names(Goethe_young))
names(Goethe_young) <- gsub(",", "", names(Goethe_young))
Goethe_young <- reduce_name_length(Goethe_young, 25)

names(Goethe_mean) <- paste("Middle", Goethe_LateStyle_corpus$first_pub[mean_sel], Goethe_LateStyle_corpus$PG_de_texts[mean_sel], sep = "_")
names(Goethe_mean) <- gsub(" ", "", names(Goethe_mean))
names(Goethe_mean) <- gsub(",", "", names(Goethe_mean))
Goethe_mean <- reduce_name_length(Goethe_mean, 25)

names(Goethe_old) <- paste("Old", Goethe_LateStyle_corpus$first_pub[old_sel], Goethe_LateStyle_corpus$PG_de_texts[old_sel], sep = "_")
names(Goethe_old) <- gsub(" ", "", names(Goethe_old))
names(Goethe_old) <- gsub(",", "", names(Goethe_old))
Goethe_old <- reduce_name_length(Goethe_old, 25)

##########
#####Other authors corpus preparation
##########

###Uniform spelling (to avoid issues with alternative spellings)
for(i in 1:length(other_authors_corpus$text)){
  tmp_string <- other_authors_corpus$text[i]
  ##substitute old S
  tmp_string <- gsub("ſ", "s", tmp_string)
  ##substitute umlauts and double S
  tmp_string <- gsub("ä", "ae", tmp_string)
  tmp_string <- gsub("ö", "oe", tmp_string)
  tmp_string <- gsub("ü", "ue", tmp_string)
  tmp_string <- gsub("ß", "ss", tmp_string)
  
  ##substitute line breaks
  tmp_string <- gsub("([a-z])-\\s+([a-z])", "\\1\\2", tmp_string)
  tmp_string <- gsub("([a-z])¬\\s+([a-z])", "\\1\\2", tmp_string)
  
  ##save new version
  other_authors_corpus$text[i] <- tmp_string
  print(i)
}

###prepare sub-corpus
other_authors <- list()
for(i in 1:length(other_authors_corpus$author)){
  other_authors[[i]] <- txt.to.words(other_authors_corpus$text[i])
}
names_tmp <- paste(other_authors_corpus$author, other_authors_corpus$title, other_authors_corpus$date, sep = "_")
names_tmp <- gsub(" ", "", names_tmp)
names(other_authors) <- gsub(",", "", names_tmp)

###subdivide in young, mean and old
other_authors_young <- other_authors[which(other_authors_corpus$date <= 1776)]
other_authors_mean <- other_authors[which(other_authors_corpus$date > 1776 & other_authors_corpus$date < 1809)]
other_authors_old <- other_authors[which(other_authors_corpus$date >= 1809)]

###get rid of short texts (limit 5,000 words)
other_authors_young <- cut_short(other_authors_young)
other_authors_mean <- cut_short(other_authors_mean)
other_authors_old <- cut_short(other_authors_old)

###anonymize all texts, in order to isolate Goethe on graphs
names(other_authors_young) <- paste("OthersY_", names(other_authors_young), sep = "")
names(other_authors_mean) <- paste("OthersM_", names(other_authors_mean), sep = "")
names(other_authors_old) <- paste("OthersO_", names(other_authors_old), sep = "")

##################
###### End of preparation, now analysis starts...
################

###Analysis with Stylo (internal analysis)

Stylo_corpus <- c(Goethe_young, Goethe_mean, Goethe_old)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Goethe_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Goethe_internal_Gephi.csv")

###Analysis with Stylo (external analysis)

##Young
Stylo_corpus <- c(Goethe_young, other_authors_young)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Goethe_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Goethe_external_young_Gephi.csv")

##Middle
Stylo_corpus <- c(Goethe_mean, other_authors_mean)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Goethe_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Goethe_external_middle_Gephi.csv")

##Old
Stylo_corpus <- c(Goethe_old, other_authors_old)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Goethe_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Goethe_external_old_Gephi.csv")

###Oppose analysis

##internal

png("Goethe_oppose_int_young_middle.png", width = 2000, height = 2000, res = 300)
oppose(gui = FALSE, primary.corpus = Goethe_young, secondary.corpus = Goethe_mean, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()

png("Goethe_oppose_int_young_old.png", width = 2000, height = 2000, res = 300)
oppose(gui = FALSE, primary.corpus = Goethe_young, secondary.corpus = Goethe_old, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()

png("Goethe_oppose_int_middle_old.png", width = 2000, height = 2000, res = 300)
oppose(gui = FALSE, primary.corpus = Goethe_mean, secondary.corpus = Goethe_old, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()

##external

png("Goethe_oppose_ext_young.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Goethe_young, secondary.corpus = other_authors_young, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()

png("Goethe_oppose_ext_middle.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Goethe_mean, secondary.corpus = other_authors_mean, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()

png("Goethe_oppose_ext_old.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Goethe_old, secondary.corpus = other_authors_old, text.slice.length=3000, text.slice.overlap=0, oppose.method="craig.zeta", visualization="markers")
dev.off()