###Note: this piece of code works with csv files that should have been generated by LIWC
###here they are named: "LIWC2015_Musil_int.csv" (LIWC analysis of the files "Musil_young_mean.txt" and "Musil_old.txt"); "LIWC2015_Musil_ext.csv" (LIWC analysis of the files "Other_authors_young_mean.txt" and "Other_authors_old.txt"), generated by the previous piece of code
###Of course, you should upload a German dictionary into LIWC: Wolf, M. et al. (2008), Computergestützte quantitative Textanalyse: Äquivalenz und Robustheit der deutschen Version des Linguistic Inquiry and Word Count, in Diagnostica 54(2):85-98

###prepare LIWC for Musil
LIWC <- read.csv("LIWC2015_Musil_int.csv")
LIWC <- as.data.frame(t(LIWC),stringsAsFactors = F)
colnames(LIWC) <- c("YoungMiddle", "Old")
LIWC <- LIWC[-1,]
LIWC[,1:2] <- lapply(LIWC[,1:2], function(x) as.numeric(x))
LIWC$difference <- abs(LIWC$Old-LIWC$YoungMiddle)
LIWC <- LIWC[with(LIWC, order(-difference)), ]
LIWC$LIWC_category <- rownames(LIWC)

LIWC_selection <- LIWC$LIWC_category[1:8]

###prepare LIWC for Others
LIWC_Others <- read.csv("LIWC2015_Musil_ext.csv")
LIWC_Others <- as.data.frame(t(LIWC_Others),stringsAsFactors = F)
LIWC_Others <- LIWC_Others[-1,]
LIWC_Others[,1:5] <- lapply(LIWC_Others[,1:5], function(x) as.numeric(x))
LIWC_Others$V1 <- (LIWC_Others$V1+LIWC_Others$V2+LIWC_Others$V3+LIWC_Others$V4)/4
LIWC_Others$V2 <- NULL
LIWC_Others$V3 <- NULL
LIWC_Others$V4 <- NULL
colnames(LIWC_Others) <- c("YoungMiddle", "Old")
LIWC_Others$LIWC_category <- rownames(LIWC_Others)

LIWC_Others <- LIWC_Others[which(LIWC_Others$LIWC_category %in% LIWC_selection),]

###compare the two
LIWC <- LIWC[1:8,]
LIWC$difference <- NULL
LIWC$author <- "Musil"
LIWC_Others$author <- "Others"
LIWC_all <- rbind(LIWC, LIWC_Others)

library(tidyverse)
library(reshape2)

LIWC_all <- melt(LIWC_all)

colnames(LIWC_all) <- c("LIWC_Category", "author", "period", "value")

p4 <- ggplot(LIWC_all) +
  geom_bar(aes(LIWC_Category, value, fill = period), stat = "identity", position = "dodge") +
  facet_wrap(~ author, nrow = 1)
p4
ggsave("Musil_LIWC_analysis.png", p4, height = 6, width = 10)
