###Musil experiment
###Note1: the "Other_authors_corpus.RData" file is too big to be hosted on Github
###Please download it from here: https://owncloud.gwdg.de/index.php/s/sO6r58SHKL6CZTg
###Note2: the network analysis graph should be generated by using Gephi (https://gephi.org/)
###The following code produces a series of csv files ("Musil_internal_Gephi.csv" et al.) to be processed with Gephi

library(stylo)
setwd("./Musil_corpus")
filenames <- list.files(path = ".", pattern="*.txt", full.names=TRUE, recursive = TRUE)

###Extra functions

dist.cosine.delta = function(x){
  # z-scoring the input matrix of frequencies
  x = scale(x)
  # computing cosine dissimilarity
  y = as.dist( x %*% t(x) / (sqrt(rowSums(x^2) %*% t(rowSums(x^2)))) )
  # then, turning it into cosine similarity
  z = 1 - y
  # getting the results
  return(z)
}

cut_short <- function(other_authors){
  short <- which(unlist(lapply(other_authors, function(x){length(x)}))<5000)
  if(length(short)>0)
     other_authors <- other_authors[-short]
  return(other_authors)
}

is.between <- function(x, range=c(a, b)) {
  x > range[1] & x < range[2]
}

reduce_name_length <- function(corpus, chars_lim = 20){
  names_tmp <- names(corpus)
  for(i in 1:length(names_tmp)){
    if(nchar(names_tmp[i])>chars_lim)
      names_tmp[i] <- paste(substr(names_tmp[i], 1, chars_lim), "...", sep = "")
  }
  names(corpus) <- names_tmp
  return(corpus)
}

##########
#####Musil corpus preparation
##########

Musil_young <- list()
Musil_middle <- list()
Musil_old <- list()

###Uniform spelling (to avoid issues with alternative spellings)
for(i in filenames){
  tmp_string <- readLines(i)
  ###Normalize text for confrontation with Kolimo (where these normalization was already applied...)
  ##substitute old S
  tmp_string <- gsub("ſ", "s", tmp_string)
  ##substitute umlauts and double S
  tmp_string <- gsub("ä", "ae", tmp_string)
  tmp_string <- gsub("ö", "oe", tmp_string)
  tmp_string <- gsub("ü", "ue", tmp_string)
  tmp_string <- gsub("ß", "ss", tmp_string)
  tmp_selection <- list(txt.to.words(tmp_string))
  names_tmp <- paste(unlist(strsplit(i, "/"))[2], "_", unlist(strsplit(i, "/"))[3], sep = "")
  names(tmp_selection) <- unlist(strsplit(names_tmp, ".txt"))[1]
  if(unlist(strsplit(i, "/"))[2] == "Old")
    Musil_old <- c(Musil_old, tmp_selection)
  if(unlist(strsplit(i, "/"))[2] == "Middle")
    Musil_middle <- c(Musil_middle, tmp_selection)
  if(unlist(strsplit(i, "/"))[2] == "Young")
    Musil_young <- c(Musil_young, tmp_selection)
}

###get rid of short texts (limit 5,000 words)
Musil_young <- cut_short(Musil_young)
Musil_middle <- cut_short(Musil_middle)
Musil_old <- cut_short(Musil_old)

##########
#####Other authors corpus preparation
##########

setwd("..")
load("Other_authors_corpus.RData")

###Uniform spelling (to avoid issues with alternative spellings)
for(i in 1:length(Kolimo_texts)){
  tmp_string <- Kolimo_texts[i]
  ##substitute old S
  tmp_string <- gsub("ſ", "s", tmp_string)
  ##substitute umlauts and double S
  tmp_string <- gsub("ä", "ae", tmp_string)
  tmp_string <- gsub("ö", "oe", tmp_string)
  tmp_string <- gsub("ü", "ue", tmp_string)
  tmp_string <- gsub("ß", "ss", tmp_string)
  
  ##substitute line breaks
  tmp_string <- gsub("([a-z])-\\s+([a-z])", "\\1\\2", tmp_string)
  tmp_string <- gsub("([a-z])¬\\s+([a-z])", "\\1\\2", tmp_string)
  
  ##save new version
  Kolimo_texts[i] <- tmp_string
  print(i)
}

###define range dates for selection
range_young=c(1906, 1917)
range_mean=c(1918, 1927)
range_old=c(1928, 1942)

###select only texts published in range (first_work/last_work)
###Young
other_authors_metadata <- full_metadata_withDates
other_authors_subcorp <- Kolimo_texts
range_dates <- range_young
works_in_range <- which(is.between(other_authors_metadata$date, range_dates))
other_authors_metadata <- other_authors_metadata[works_in_range,]
other_authors_subcorp <- other_authors_subcorp[works_in_range]

###prepare corpus for Stylo
other_authors_corpus <- list()
for(i in 1:length(other_authors_subcorp)){
  tmp_selection <- list(txt.to.words(other_authors_subcorp[i]))
  names_tmp <- paste(other_authors_metadata$author[i], other_authors_metadata$title[i], other_authors_metadata$date[i], sep = "_")
  names_tmp <- gsub(",", "", names_tmp)
  names_tmp <- gsub("\n", "Anon", names_tmp)
  names(tmp_selection) <- gsub(" ", "", names_tmp)
  other_authors_corpus <- c(other_authors_corpus, tmp_selection) 
  print(i)
}
other_authors_young <- other_authors_corpus
###anonymize all other texts, in order to isolate Goethe on graphs
names(other_authors_young) <- paste("OthersY_", names(other_authors_young), sep = "")

###select only texts published in range (first_work/last_work)
###Middle Age
other_authors_metadata <- full_metadata_withDates
other_authors_subcorp <- Kolimo_texts
range_dates <- range_mean
works_in_range <- which(is.between(other_authors_metadata$date, range_dates))
other_authors_metadata <- other_authors_metadata[works_in_range,]
other_authors_subcorp <- other_authors_subcorp[works_in_range]
###prepare corpus for Stylo
other_authors_corpus <- list()
for(i in 1:length(other_authors_subcorp)){
  tmp_selection <- list(txt.to.words(other_authors_subcorp[i]))
  names_tmp <- paste(other_authors_metadata$author[i], other_authors_metadata$title[i], other_authors_metadata$date[i], sep = "_")
  names_tmp <- gsub(",", "", names_tmp)
  names_tmp <- gsub("\n", "Anon", names_tmp)
  names(tmp_selection) <- gsub(" ", "", names_tmp)
  other_authors_corpus <- c(other_authors_corpus, tmp_selection) 
  print(i)
}
other_authors_middle <- other_authors_corpus
###anonymize all other texts, in order to isolate Goethe on graphs
names(other_authors_middle) <- paste("OthersM_", names(other_authors_middle), sep = "")

###select only texts published in range (first_work/last_work)
###Old
other_authors_metadata <- full_metadata_withDates
other_authors_subcorp <- Kolimo_texts
range_dates=range_old
works_in_range <- which(is.between(other_authors_metadata$date, range_dates))
other_authors_metadata <- other_authors_metadata[works_in_range,]
other_authors_subcorp <- other_authors_subcorp[works_in_range]
###prepare corpus for Stylo
other_authors_corpus <- list()
for(i in 1:length(other_authors_subcorp)){
  tmp_selection <- list(txt.to.words(other_authors_subcorp[i]))
  names_tmp <- paste(other_authors_metadata$author[i], other_authors_metadata$title[i], other_authors_metadata$date[i], sep = "_")
  names_tmp <- gsub(",", "", names_tmp)
  names_tmp <- gsub("\n", "Anon", names_tmp)
  names(tmp_selection) <- gsub(" ", "", names_tmp)
  other_authors_corpus <- c(other_authors_corpus, tmp_selection) 
  print(i)
}
other_authors_old <- other_authors_corpus
###anonymize all other texts, in order to isolate Goethe on graphs
names(other_authors_old) <- paste("OthersO_", names(other_authors_old), sep = "")

###get rid of short texts (limit 5,000 words)
other_authors_young <- cut_short(other_authors_young)
other_authors_middle <- cut_short(other_authors_middle)
other_authors_old <- cut_short(other_authors_old)

###############
###Internal analysis
############

Stylo_corpus <- c(Musil_young, Musil_middle, Musil_old)
stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Musil_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Musil_internal_Gephi.csv")

###############
###External analysis
############

##Young
Stylo_corpus <- c(Musil_young, other_authors_young)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Musil_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Musil_external_young_Gephi.csv")

##Middle
Stylo_corpus <- c(Musil_middle, other_authors_middle)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Musil_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Musil_external_middle_Gephi.csv")

##Old
Stylo_corpus <- c(Musil_old, other_authors_old)
results.stylo <- stylo(gui = FALSE, corpus.lang="German", analysis.type="CA", mfw.min=2000, mfw.max=2000, mfw.incr=0, distance.measure="dist.cosine.delta", write.pdf.file = FALSE, parsed.corpus = Stylo_corpus)
###rename output csv file for analysis with Gephi
file.rename("Musil_CA_2000_MFWs_Culled_0__dist.cosine.delta_EDGES.csv", "Musil_external_old_Gephi.csv")

###################
###Oppose analysis
############

##Just external...
png("Musil_oppose_ext_old.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Musil_old, secondary.corpus = other_authors_old)
dev.off()

png("Musil_oppose_ext_middle.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Musil_middle, secondary.corpus = other_authors_middle)
dev.off()

png("Musil_oppose_ext_young.png", width = 2000, height = 2000, res = 300)
oppose(primary.corpus = Musil_young, secondary.corpus = other_authors_young)
dev.off()